/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHotspotFeaturesRouteImport } from './routes/api/hotspot-features'
import { Route as ApiGlbProxyRouteImport } from './routes/api/glb-proxy'
import { Route as ApiGenerateOutfitRouteImport } from './routes/api/generate-outfit'
import { Route as ApiGenerate3dRouteImport } from './routes/api/generate-3d'
import { Route as ApiAdCopyRouteImport } from './routes/api/ad-copy'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotspotFeaturesRoute = ApiHotspotFeaturesRouteImport.update({
  id: '/api/hotspot-features',
  path: '/api/hotspot-features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlbProxyRoute = ApiGlbProxyRouteImport.update({
  id: '/api/glb-proxy',
  path: '/api/glb-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateOutfitRoute = ApiGenerateOutfitRouteImport.update({
  id: '/api/generate-outfit',
  path: '/api/generate-outfit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerate3dRoute = ApiGenerate3dRouteImport.update({
  id: '/api/generate-3d',
  path: '/api/generate-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdCopyRoute = ApiAdCopyRouteImport.update({
  id: '/api/ad-copy',
  path: '/api/ad-copy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ad-copy': typeof ApiAdCopyRoute
  '/api/generate-3d': typeof ApiGenerate3dRoute
  '/api/generate-outfit': typeof ApiGenerateOutfitRoute
  '/api/glb-proxy': typeof ApiGlbProxyRoute
  '/api/hotspot-features': typeof ApiHotspotFeaturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ad-copy': typeof ApiAdCopyRoute
  '/api/generate-3d': typeof ApiGenerate3dRoute
  '/api/generate-outfit': typeof ApiGenerateOutfitRoute
  '/api/glb-proxy': typeof ApiGlbProxyRoute
  '/api/hotspot-features': typeof ApiHotspotFeaturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ad-copy': typeof ApiAdCopyRoute
  '/api/generate-3d': typeof ApiGenerate3dRoute
  '/api/generate-outfit': typeof ApiGenerateOutfitRoute
  '/api/glb-proxy': typeof ApiGlbProxyRoute
  '/api/hotspot-features': typeof ApiHotspotFeaturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/ad-copy'
    | '/api/generate-3d'
    | '/api/generate-outfit'
    | '/api/glb-proxy'
    | '/api/hotspot-features'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/ad-copy'
    | '/api/generate-3d'
    | '/api/generate-outfit'
    | '/api/glb-proxy'
    | '/api/hotspot-features'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/ad-copy'
    | '/api/generate-3d'
    | '/api/generate-outfit'
    | '/api/glb-proxy'
    | '/api/hotspot-features'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdCopyRoute: typeof ApiAdCopyRoute
  ApiGenerate3dRoute: typeof ApiGenerate3dRoute
  ApiGenerateOutfitRoute: typeof ApiGenerateOutfitRoute
  ApiGlbProxyRoute: typeof ApiGlbProxyRoute
  ApiHotspotFeaturesRoute: typeof ApiHotspotFeaturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotspot-features': {
      id: '/api/hotspot-features'
      path: '/api/hotspot-features'
      fullPath: '/api/hotspot-features'
      preLoaderRoute: typeof ApiHotspotFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/glb-proxy': {
      id: '/api/glb-proxy'
      path: '/api/glb-proxy'
      fullPath: '/api/glb-proxy'
      preLoaderRoute: typeof ApiGlbProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-outfit': {
      id: '/api/generate-outfit'
      path: '/api/generate-outfit'
      fullPath: '/api/generate-outfit'
      preLoaderRoute: typeof ApiGenerateOutfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-3d': {
      id: '/api/generate-3d'
      path: '/api/generate-3d'
      fullPath: '/api/generate-3d'
      preLoaderRoute: typeof ApiGenerate3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ad-copy': {
      id: '/api/ad-copy'
      path: '/api/ad-copy'
      fullPath: '/api/ad-copy'
      preLoaderRoute: typeof ApiAdCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdCopyRoute: ApiAdCopyRoute,
  ApiGenerate3dRoute: ApiGenerate3dRoute,
  ApiGenerateOutfitRoute: ApiGenerateOutfitRoute,
  ApiGlbProxyRoute: ApiGlbProxyRoute,
  ApiHotspotFeaturesRoute: ApiHotspotFeaturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
